// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProductivityShell
{
    static class Vsix
    {
        public const string Id = "b86685dd-7fdb-4ee5-bacc-647c4f42168d";
        public const string Name = "Productivity Shell";
        public const string Description = @"Productivity tools for Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.3";
        public const string Author = "jfevia";
        public const string Tags = "Productivity, Command, GUID, WiX, Tools, Build, Time Savers, refactor, jfevia";
    }
}
