// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProductivityShell
{
    static class Vsix
    {
        public const string Id = "ProductivityShell";
        public const string Name = "Productivity Shell";
        public const string Description = @"Productivity tools for Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "jfevia";
        public const string Tags = "Productivity, Command, Macros, Script, GUID, WiX, Tools, Build, Time Savers";
    }
}
